"""RAMP L1 protocol-mechanics helpers (ADR-020 tree sdk/{go,ts,python}/).

Stateless, IO-free protocol mechanics — RFC 7638 thumbprint, Ed25519 signed-URL
verify, RFC 9421 request sign/verify + GET proof-of-possession (both faces),
offer-acceptance sign/verify, base64url codec, and cross-field (message-CEL)
validation — byte-parity-guarded against the sdk/go oracle. Clock and key
resolution are injected (ADR-020 §1/§4); the helpers hold no state and touch no
IO.

Acceptance canonicalization is JCS (RFC 8785): the canonical names are the
``*_jcs`` forms from :mod:`ramp_sdk.core`; the unsuffixed names are aliases kept
for continuity (see :mod:`ramp_sdk.acceptance`).

``Client`` and ``BrokerClient`` re-exported here are the ASYNC faces, which are the
core; the blocking facade lives at :mod:`ramp_sdk.sync` under the same names and is
not flattened into this namespace, because two classes called ``Client`` in one
namespace would make the choice between them a matter of which import won.
"""

from __future__ import annotations

from .acceptance import (
    canonical_acceptance_payload,
    sign_offer_acceptance,
    verify_offer_acceptance,
)
from .b64 import b64url_decode, b64url_nopad
from .client import (
    BrokerClient,
    CallError,
    CallErrorKind,
    CatalogClient,
    Client,
    ClientConfig,
    Content,
    EndpointResolver,
    Validation,
)
from .core import (
    ACCEPTANCE_SIGNATURE_ALGORITHM,
    OFFER_SIGNATURE_ALGORITHM,
    DiscoveryResult,
    Mode,
    OfferGroupResult,
    RejectedOffer,
    Result,
    VerifiedOffer,
    Verifier,
    canonical_offer_payload,
    jcs_acceptance_payload,
    sign_offer_acceptance_jcs,
    sign_offer_jcs,
    verify_offer_acceptance_jcs,
)
from .crossfield import cross_field_rule_ids
from .errordetail import (
    ERROR_DETAIL_TYPE,
    REASON_FIELDS,
    catalog_rejection_detail,
    dispute_failure_detail,
    domain_verification_failure_detail,
    error_detail_from,
    parse_error_detail,
    reason,
    registration_failure_detail,
    retrieval_auth_failure_detail,
    transaction_denial_detail,
    usage_report_rejection_detail,
)
from .hashurl import hash_url
from .hosts import (
    BARE_DOMAIN_PATTERN,
    MAX_BARE_DOMAIN_LEN,
    AudienceVerdict,
    check_audience,
    host_anchored,
    host_of,
    is_bare_domain,
    is_bare_host,
)
from .httpsig import (
    MultisigVerdict,
    RejectReason,
    ReplayStore,
    append_signature,
    content_digest,
    sign_request,
    verify_multisig_request_server,
    verify_request,
    verify_request_server,
)
from .idempotency import generate_idempotency_key, validate_idempotency_key
from .keyresolver import KeyResolver, StaticKeyResolver
from .licenseterm import (
    RULE_OBLIGATION_OTHER_REQUIRES_DETAIL,
    RULE_PRICING_UNIT_REGISTERED,
    RULE_QUOTA_METRIC_REGISTERED,
    RULE_RESTRICTION_CANONICAL_DISJOINT,
    RULE_RESTRICTION_TOKEN_REGISTERED,
    EntryVerdict,
    RuleViolation,
    RuleWarning,
    TermVerdict,
    canonical_restriction_token,
    known_restriction_token,
    normalize_license_term,
    normalize_resource_entry,
    validate_license_term,
    validate_resource_entry,
)
from .money import canonicalize_money, format_money, parse_money
from .pop import AGENT_KEY_HEADER, sign_agent_binding, verify_agent_binding
from .regschema import (
    MAX_REGISTRATION_DATA_BYTES,
    MAX_REGISTRATION_DATA_DEPTH,
    MAX_REGISTRATION_DATA_MEMBERS,
    MAX_REGISTRATION_FIELD_ERROR_PATH_LEN,
    MAX_REGISTRATION_FIELD_ERROR_TEXT_LEN,
    MAX_REGISTRATION_FIELD_ERRORS,
    MAX_REGISTRATION_SCHEMA_BYTES,
    MAX_REGISTRATION_SCHEMA_DEPTH,
    MAX_REGISTRATION_SCHEMA_EVALUATIONS,
    MAX_REGISTRATION_SCHEMA_REF_HOPS,
    REGISTRATION_SCHEMA_DIALECT,
    RegistrationDataVerdict,
    RegistrationSchema,
    SchemaVerdict,
    check_registration_data,
    compile_registration_schema,
    is_safe_schema_pattern,
)
from .resolvers import (
    WBA_DIRECTORY_PATH,
    DirectoryUnavailableError,
    EndpointRefusedError,
    KeyExpiredError,
    KeyRevokedError,
    NoEndpointError,
    ResolverError,
    UnknownKeyError,
    WBAKeyResolver,
    WellKnownEndpointResolver,
    WellKnownKeyResolver,
    wba_directory_url,
)
from .scopes import apply_scopes, normalize_scopes, scopes_subset
from .signedurl import sign_ed25519_signed_url, verify_ed25519_signed_url
from .signing_transport import SignedOutbound, SigningTransport
from .thumbprint import thumbprint
from .window import Window, clock_window, monotonic_window
from .wire import (
    ConnectProtocolVersion,
    ConnectProtocolVersionHeader,
    ContentTypeJSON,
    ContentTypeProto,
    ProtocolVersion,
    RequestIDHeader,
    SignatureAgentHeader,
)

__all__ = [
    "ACCEPTANCE_SIGNATURE_ALGORITHM",
    "AGENT_KEY_HEADER",
    "AudienceVerdict",
    "BARE_DOMAIN_PATTERN",
    "BrokerClient",
    "CallError",
    "CallErrorKind",
    "CatalogClient",
    "Client",
    "ClientConfig",
    "ConnectProtocolVersion",
    "ConnectProtocolVersionHeader",
    "Content",
    "ContentTypeJSON",
    "ContentTypeProto",
    "DirectoryUnavailableError",
    "DiscoveryResult",
    "ERROR_DETAIL_TYPE",
    "EndpointRefusedError",
    "EndpointResolver",
    "EntryVerdict",
    "KeyExpiredError",
    "KeyResolver",
    "KeyRevokedError",
    "MAX_BARE_DOMAIN_LEN",
    "MAX_REGISTRATION_DATA_BYTES",
    "MAX_REGISTRATION_DATA_DEPTH",
    "MAX_REGISTRATION_DATA_MEMBERS",
    "MAX_REGISTRATION_FIELD_ERRORS",
    "MAX_REGISTRATION_FIELD_ERROR_PATH_LEN",
    "MAX_REGISTRATION_FIELD_ERROR_TEXT_LEN",
    "MAX_REGISTRATION_SCHEMA_BYTES",
    "MAX_REGISTRATION_SCHEMA_DEPTH",
    "MAX_REGISTRATION_SCHEMA_EVALUATIONS",
    "MAX_REGISTRATION_SCHEMA_REF_HOPS",
    "Mode",
    "MultisigVerdict",
    "NoEndpointError",
    "OFFER_SIGNATURE_ALGORITHM",
    "OfferGroupResult",
    "ProtocolVersion",
    "REASON_FIELDS",
    "REGISTRATION_SCHEMA_DIALECT",
    "RULE_OBLIGATION_OTHER_REQUIRES_DETAIL",
    "RULE_PRICING_UNIT_REGISTERED",
    "RULE_QUOTA_METRIC_REGISTERED",
    "RULE_RESTRICTION_CANONICAL_DISJOINT",
    "RULE_RESTRICTION_TOKEN_REGISTERED",
    "RegistrationDataVerdict",
    "RegistrationSchema",
    "RejectReason",
    "RejectedOffer",
    "ReplayStore",
    "RequestIDHeader",
    "ResolverError",
    "Result",
    "RuleViolation",
    "RuleWarning",
    "SchemaVerdict",
    "SignatureAgentHeader",
    "SignedOutbound",
    "SigningTransport",
    "StaticKeyResolver",
    "TermVerdict",
    "UnknownKeyError",
    "Validation",
    "VerifiedOffer",
    "Verifier",
    "WBAKeyResolver",
    "WBA_DIRECTORY_PATH",
    "WellKnownEndpointResolver",
    "WellKnownKeyResolver",
    "Window",
    "append_signature",
    "apply_scopes",
    "b64url_decode",
    "b64url_nopad",
    "canonical_acceptance_payload",
    "canonical_offer_payload",
    "canonical_restriction_token",
    "canonicalize_money",
    "catalog_rejection_detail",
    "check_audience",
    "check_registration_data",
    "clock_window",
    "compile_registration_schema",
    "content_digest",
    "cross_field_rule_ids",
    "dispute_failure_detail",
    "domain_verification_failure_detail",
    "error_detail_from",
    "format_money",
    "generate_idempotency_key",
    "hash_url",
    "host_anchored",
    "host_of",
    "is_bare_domain",
    "is_bare_host",
    "is_safe_schema_pattern",
    "jcs_acceptance_payload",
    "known_restriction_token",
    "monotonic_window",
    "normalize_license_term",
    "normalize_resource_entry",
    "normalize_scopes",
    "parse_error_detail",
    "parse_money",
    "reason",
    "registration_failure_detail",
    "retrieval_auth_failure_detail",
    "scopes_subset",
    "sign_agent_binding",
    "sign_ed25519_signed_url",
    "sign_offer_acceptance",
    "sign_offer_acceptance_jcs",
    "sign_offer_jcs",
    "sign_request",
    "thumbprint",
    "transaction_denial_detail",
    "usage_report_rejection_detail",
    "validate_idempotency_key",
    "validate_license_term",
    "validate_resource_entry",
    "verify_agent_binding",
    "verify_ed25519_signed_url",
    "verify_multisig_request_server",
    "verify_offer_acceptance",
    "verify_offer_acceptance_jcs",
    "verify_request",
    "verify_request_server",
    "wba_directory_url",
]
